### PR TITLE
Setup jest and add unit tests

### PR DESCRIPTION
**Pull request by aneeshrelan**
Implements #8 

Adds a jest setup with typescript and adds a unit test for all library methods with a very high unit test coverage

### CODE REVIEW

**Comment by aneeshrelan** [comment]
@buzz-js Let me know if this style of unit tests are okay. Thanks!

**Comment by buzz-js** [comment]
> @buzz-js Let me know if this style of unit tests are okay. Thanks!

The `update` and `delete` method has changed, can you take a look at the last commit?

**Comment by aneeshrelan** [comment]
> > @buzz-js Let me know if this style of unit tests are okay. Thanks!
> 
> The `delete` method has changed, can you take a look at the last commit?

Sure. Will incorporate the changes

**Comment by buzz-js** [comment]
> > > @buzz-js Let me know if this style of unit tests are okay. Thanks!
> > 
> > 
> > The `delete` method has changed, can you take a look at the last commit?
> 
> Sure. Will incorporate the changes

Don't worry, I've already changed it. Thank you very much for your great contribution to the project ✨

**Comment by aneeshrelan** [comment]
Awesome. Thanks! Let me know if I can assist on any other aspects as well

**Comment by buzz-js** [comment]
> Awesome. Thanks! Let me know if I can assist on any other aspects as well

I still need to modify the update method, I would appreciate a lot of help

**Comment by aneeshrelan** [comment]
Sure. I can give it a shot. Would you mind specifying the requirements, I can take them up in a few days

**Comment by buzz-js** [comment]
> Sure. I can give it a shot. Would you mind specifying the requirements, I can take them up in a few days

Sure, I'll think about it and send it to you

**Comment by buzz-js** [comment]
@all-contributors please add @aneeshrelan for tests and code

**Pull request merged**
