### PR TITLE
Add mongo-like filters implementation

### PR DESCRIPTION
**Pull request by fr0stylo**

### CODE REVIEW

**Comment by buzz-js** [comment]
@fr0stylo Thank you very much for your contribution, this is a very important feature 💯💯

**Comment by buzz-js** [comment]
@all-contributors please add @fr0stylo  for infrastructure and code

**Comment by buzz-js** [comment]
@fr0stylo Hi, there is an error in the find method, in specific $in query

There are two categories: Dinner and Drinks

Execute: 

```
lsdb.find("categories", {
  where: {
    title: { $in: ["er", "ks"] },
   },
})
```

Expected result: 

```
categories: Array(2)

0: {_id: 0, title: "Dinner"}
1: {_id: 0, title: "Drinks"}
```

**Comment by fr0stylo** [comment]
Updated here https://github.com/buzz-js/lsdb/pull/21. I forgot that $in value are array :)

**Comment by buzz-js** [comment]
> Updated here #21. I forgot that $in value are array :)

It should also work in deep query...

Example:
**entry  article has property tags**
```
article: {
    tags: ["css","js"]
}

```
```
lsdb.find("articles", {
  where: {
    tags: { $in: ["css"] },
   },
 deep: true
})
```

**Comment by fr0stylo** [comment]
By saying deep you mean full match or partial match on value ? As example gives full match

**Comment by buzz-js** [comment]
> By saying deep you mean full match or partial match on value ? As example gives full match

For now the filters work with string or number, when I say deep, I mean looking for values within a property that contains an array, it can be string or numbers.

```
{
 title: "Drinks",
 tag: ["css","js"]
}
```

**The user can search by article title or by articles that contain the css tag**

**Pull request merged**
